[pytest]
testpaths = tests
addopts =
    -v
    --browser chromium
    --screenshot only-on-failure
    --output reports/artifacts
    --html=reports/report.html
    --self-contained-html
pythonpath = .
